application/backendApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Routing of our Django App

urlpatterns = [
    # anything going to '/' should be redirected to the urls of imageupload_frontend
    url(r'^', include('frontendApp.urls', namespace='frontendApp')),
    url(r'^', include('restApp.urls', namespace='restApp')),
    # anything going to /admin gets redirected to the admin stuff (makes sense...)
    url(r'^admin/', admin.site.urls),
    # anything going to /api gets redirected to the django rest API stuff
    url(r'^api/', include('restApp.urls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# we are serving static and media files here at the moment - if we deploy this app to a server, we do necessarily want this

application/frontendApp/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from .views import *

# Redirect any request that goes into here to static/index.html
urlpatterns = [
    url(r'^$', Top15.as_view(), name='top15'),
    url(r'^produktai/', Products.as_view(), name='products'),
    url(r'^naujas_produktas/', CreateProduct.as_view(), name='createProduct'),
    url(r'^produktas/', ViewProduct.as_view(), name='viewProduct'),
    url(r'^prekeszenklai/', Brands.as_view(), name='brands'),
    url(r'^ingredientai/', Ingredients.as_view(), name='ingredients'),

    url(r'^odos-testas/', SkinTest.as_view(), name='skintest'),
    url(r'^profilis/', Profile.as_view(), name='profile'),
    url(r'^registracija/', Register.as_view(), name='register'),

    url(r'^', include('django.contrib.auth.urls')),
    url(r'^logoff/$', LogoffView, name='logoff'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/restApp/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from restApp.viewsets import *

from rest_framework.routers import DefaultRouter

# initiate router and register all endpoints
router = routers.DefaultRouter()

router.register(r'brands', BrandViewSet)
router.register(r'brands_list', BrandListViewSet)
router.register(r'ingredients', IngredientsViewSet)
router.register(r'products', ProductViewSet)
router.register(r'product', ProductDetailsViewSet)
router.register(r'productSearch', ProductViewSearchSet)
router.register(r'brandDetails', BrandDetailsViewSet)

router.register(r'commentsbrand',   CommentBrandViewSet)
router.register(r'commentsproduct', CommentProductViewSet)
router.register(r'createcomment', CreateCommentViewSet)

#top15 urls
router.register(r'postrank', postRankViewSet)
router.register(r'topbrands', topBrandsViewSet)
router.register(r'topproducts', topProductsViewSet)
router.register(r'topusers', topUsersViewSet)

# Wire up our API with our urls
urlpatterns = [
    url(r'^', include(router.urls)),
]

application/frontendApp/forms.py
from django.contrib.auth.models import User
from django import forms

class ClientLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password']

application/frontendApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, status, filters
from restApp.serializers import *
from modelsViews.models import *
from .forms import ClientLoginForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

class Top15(TemplateView):
    template_name = 'top15.html'
class Ingredients(TemplateView):
    template_name = 'ingredients.html'
class Products(TemplateView):
    template_name = 'products.html'
class ViewProduct(TemplateView):
    template_name = 'viewProduct.html'
class Brands(TemplateView):
    template_name = 'brands.html'
class Profile(TemplateView):
    template_name = 'profile.html'
class SkinTest(TemplateView):
    template_name = 'skinTest.html'
class Register(TemplateView):
    template_name = 'register.html'
class CreateProduct(TemplateView):
    template_name = 'createProduct.html'

def ClientAccView(request):
    if request.user.is_authenticated:
      return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
      return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class ClientFormView(View):
    form_class = ClientLoginForm

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def LogoffView(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

application/frontendApp/templates/brands.html
{% include 'header.html' %}
<div ng-controller="SearchCtrl"
     ng-init="init('/api/brands_list/', '?search=')"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_9">
      <div class="content">
        <div class="block1">
          <input class="searchInput" placeholder="Pagal pavadinimą, el. pašto adresą, tinklavietę" type="search" ng-model="searchVar"></input>
          <button ng-click="search(searchVar)">Ieškoti</button>
          </br><a ng-cloak>Rasta: {[{ searchResults.count }]}</a>
          <div ng-hide="recordsExist" class="ng-hide">
            <a href="" ng-click="anotherPage(pageNo-1)" class="btn">< Ankstesnis</a>
            <a href="" ng-cloak ng-repeat="page in pageList track by $index"  ng-click="anotherPage(page)" class="btn">{[{page}]}</a>
            <a href="" ng-click="anotherPage(pageNo+1)" class="btn">Sekantis ></a>
          </div>
        </div>
      </div>
    </div>
    <div class="grid_3">
      <h1><a href="{% url 'frontendApp:top15' %}"><img src="../static/images/logo.png" alt=""></a></h1>
    </div>
    <div class="grid_9">
      <div class="content">
        <div ng-hide="recordsExist" class="ng-hide" class="block1" ng-cloak>
          <div>
            <h3>Prekės ženklai:</h3>
            <ul style="list-style: none;"  ng-cloak>
              <li class="grid_9" ng-repeat="brand in searchResults.results">
                <div class="grid_2 alpha">
                  <img style="max-width: 120px;" src="{[{ brand.thumbnail }]}"></img>
                </div>
                <div class="grid_5">
                  </br>
                  <a href="/profilis/{[{brand.pk}]}">{[{ brand.brandName }]}</a></br></br>
                  <a ng-cloak href=""
                     ng-click="showDetails = ! showDetails; changeSign(showDetails, $index)">Aprašymas: <c id="sign{[{$index}]}">+<c>
                     </br>
                  </a>
                  <div ng-show="showDetails">
                    {[{ brand.tagLine }]}
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div ng-hide="!recordsExist" class="ng-hide" class="block1" ng-cloak>
          <h4>Pagal paieškos įvestį duomenų nerasta.. </h4>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}

application/frontendApp/templates/createProduct.html
{% include 'header.html' %}
<div ng-controller="CreateProductCtrl"
     ng-init="init('/api/ingredients/', '?search=', '/api/products/?search=')"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_9">
      <div class="content">
        <div ng-cloak class="block1">
          {% if user.isBrand %}
          <h3>Naujas produktas</h3>
          <ul ng-clock>
            <li><img id="imagePreview" src="#" alt=""></li>
            <li><input file-model="myFile" type="file" id="files" class="ng-hide"/><li>
            <li><label class="pointer" for="files">Pridėti produkto logotipą > *</label></li>
            <li class="red">{[{ errors.image }]}</li>
            <li><input ng-model="newProductModel.name" class="registerForm" maxlength="128" name="name" type="text" placeholder="Produkto pavadinimas">*</li>
            <li class="red">{[{ errors.name }]}</li>
            <li><textarea ng-model="newProductModel.tagLine" class="registerForm" rows="10" placeholder="Trumpas produkto aprašymas"></textarea>*</li>
            <li class="red">{[{ errors.tagLine }]}</li>
            <li><h4>Pasirinkti ingredientai:</h4></li>
            <li class="red">{[{ errors.ingredients }]}</li>
            <li ng-repeat="attachedIngredient in attachedIngredients">
              {[{ attachedIngredient.name }]}
              <img ng-click="remIngredient(attachedIngredient.pk)" class="pointer miniBtn" src="/media/x.png">
            </li>
            <li>
              <h4>Pasirinkite ingredientus iš sąrašo:</h4>
              <input class="searchInput" placeholder="Pagal pavadinimą, nuorodos, CAS, EC numerius" type="search" ng-model="searchVar"></input>
              <button ng-click="search(searchVar)">Ieškoti</button>
              </br><a ng-cloak>Rasta: {[{ searchResults.count }]}</a>
              <div ng-hide="recordsExist" class="ng-hide">
                <a href="" ng-click="anotherPage(pageNo-1)" class="btn">< Ankstesnis</a>
                <a href="" ng-cloak ng-repeat="page in pageList track by $index"  ng-click="anotherPage(page)" class="btn">{[{page}]}</a>
                <a href="" ng-click="anotherPage(pageNo+1)" class="btn">Sekantis ></a>
              </div>
              </br>
              <div ng-hide="recordsExist" class="ng-hide" class="block1" ng-cloak>
                <div>
                  <ul class="list" ng-cloak>
                    <li ng-repeat="ingredient in searchResults.results">
                      {[{ ingredient.referenceNumber }]} {[{ ingredient.name }]}
                      <img ng-click="addIngredient(ingredient.pk, ingredient.name)" class="pointer miniBtn" src="/media/plus.png">
                    </li>
                  </ul>
                </div>
              </div>
              <div ng-hide="!recordsExist" class="ng-hide" class="block1" ng-cloak>
                <h4>Pagal paieškos įvestį duomenų nerasta.. </h4>
              </div>
              <div class="clear"></div>
            </li>
            <li><a ng-click="createProduct({{ user.pk }})" class="btn">Kurti</a></li>
          </ul>
          {% else %}
          <h4>Produktus kurti gali tik naudotojai turintys prekės ženklo sąsają</h4>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="grid_3">
      <h1><a href="{% url 'frontendApp:top15' %}"><img src="../static/images/logo.png" alt=""></a></h1>
    </div>
  </div>
</div>
{% include 'footer.html' %}

application/frontendApp/templates/footer.html
</br></br></br></br></br>
<footer>
  <div class="container_12">
    <div class="grid_12">
      <div><h4>Rokas Ščepanovas © 2018</h4></div>
    </div>
  </div>
</footer>
</body>
<!-- Angular libraries -->
<script src="../static/node_modules/angular/angular.js"></script>
<script src="../static/node_modules/angular-resource/angular-resource.min.js"></script>
<script src="../static/node_modules/ng-file-upload/dist/ng-file-upload.min.js"></script>
<script src="../static/node_modules/angular-animate/angular-animate.min.js"></script>
<script src="../static/node_modules/angularjs-toaster/toaster.js"></script>
<script src="../static/node_modules/angular-route/angular-route.js"></script>
<script src="../static/node_modules/angular-cookies/angular-cookies.js"></script>
<script src="../static/node_modules/angular-ui-router/angular-ui-router.js"></script>
<!-- App -->
<script src="../static/js/mainApp.js"></script>
<script src="../static/js/image.js"></script>
<script src="../static/js/displayImageInCreateForm.js"></script>
<script src="../static/js/search.js"></script>
<script src="../static/js/top15.js"></script>
<script src="../static/js/register.js"></script>
<script src="../static/js/profile.js"></script>
<script src="../static/js/createProduct.js"></script>
<script src="../static/js/viewProduct.js"></script>
<script src="../static/js/skinTest.js"></script>
</html>

application/frontendApp/templates/header.html
{% load urlTag %}
{% url 'frontendApp:top15' as top15 %}
{% url 'frontendApp:products' as products %}
{% url 'frontendApp:brands' as brands %}
{% url 'frontendApp:ingredients' as ingredients %}
{% url 'frontendApp:skintest' as skintest %}
{% url 'frontendApp:profile' as profile %}
{% url 'frontendApp:createProduct' as createProduct %}
<!DOCTYPE html>
<html lang="lt">
<head>
<title>Kosmetika</title>
<meta charset="utf-8">
<link rel="icon" href="../static/images/favicon.ico">
<link rel="shortcut icon" href="static/images/favicon.ico">
<link rel="stylesheet" href="../static/css/style.css">
<link rel="../static/node_modules/angular/angular-csp.css">
<link rel="stylesheet" href="../static/node_modules/angularjs-toaster/toaster.min.css">
<script src="../static/js/jquery.js"></script>
<script src="../static/js/jquery-migrate-1.1.1.js"></script>
<script src="../static/js/superfish.js"></script>
<script src="../static/js/jquery.equalheights.js"></script>
<script src="../static/js/jquery.easing.1.3.js"></script>
</head>
<header>
  <div class="menu_block">
    <div class="container_12">
      <div class="grid_12">
        {% if not user.is_authenticated %}
        <form id="login-form" action="/login/" method="post">{% csrf_token %}
          <input id="username" name="username" type="text" placeholder="Slapyvardis" required>
          <input id="password" name="password" type="password" placeholder="Slaptažodis" required>
          <button type="submit">Prisijungti</button>
          <a id="register" href="{% url 'frontendApp:register' %}">Registruotis</a>
        </form>
        {% endif %}
        {% if user.is_authenticated %}
        <a id="logoff" href="/logoff/">Atsijungti</a>
        <ul class="sf-menu" id="sf-menu-right">
          {% if user.isBrand %}
          <li class="{% active request createProduct %}">
            <a href="{% url 'frontendApp:createProduct' %}">Naujas produktas</a></li>
          {% else %}
          <li class="{% active request skintest %}">
            <a href="{% url 'frontendApp:skintest' %}">Odos testas</a></li>
          {% endif %}
          <li  class="{% active request profile %}">
             <a href="{% url 'frontendApp:profile' %}">{{ request.user.username }}</a>
         </li>{% csrf_token %}
        </ul>
        {% endif %}
        <nav>
          <ul class="sf-menu">
            <li class="{% active request top15 %}">
              <a href="{% url 'frontendApp:top15' %}">Titulinis</a></li>
            <li class="{% active request products %}">
              <a href="{% url 'frontendApp:products' %}">Produktai</a></li>
            <li class="{% active request brands %}">
              <a href="{% url 'frontendApp:brands' %}">Prekės ženklai</a></li>
            <li class="{% active request ingredients %}">
              <a href="{% url 'frontendApp:ingredients' %}">Ingredientai</a></li>
          </ul>
        </nav>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>
<body class="page1" ng-app="mainApp">
  <toaster-container></toaster-container>

application/frontendApp/templates/ingredients.html
{% include 'header.html' %}
<div ng-controller="SearchCtrl"
     ng-init="init('/api/ingredients/', '?search=')"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_9">
      <div class="content">
        <div class="block1">
          <input class="searchInput" placeholder="Pagal pavadinimą, nuorodos, CAS, EC numerius" type="search" ng-model="searchVar"></input>
          <button ng-click="search(searchVar)">Ieškoti</button>
          </br><a ng-cloak>Rasta: {[{ searchResults.count }]}</a>
          <div ng-hide="recordsExist" class="ng-hide">
            <a href="" ng-click="anotherPage(pageNo-1)" class="btn">< Ankstesnis</a>
            <a href="" ng-cloak ng-repeat="page in pageList track by $index"  ng-click="anotherPage(page)" class="btn">{[{page}]}</a>
            <a href="" ng-click="anotherPage(pageNo+1)" class="btn">Sekantis ></a>
          </div>
        </div>
      </div>
    </div>
    <div class="grid_3">
      <h1><a href="{% url 'frontendApp:top15' %}"><img src="../static/images/logo.png" alt=""></a></h1>
    </div>
    <div class="grid_9">
      <div class="content">
          <div ng-hide="recordsExist" class="ng-hide" class="block1" ng-cloak>
            <div>
              <h3>Ingredientai:</h3>
              <ul class="list" ng-cloak>
                <li ng-repeat="ingredient in searchResults.results">
                  <a href="" ng-click="showDetails = ! showDetails">{[{ ingredient.name }]}</a>
                  <p class="ingredientsDetails" ng-show="showDetails">
                    Nuorodos numeris: {[{ ingredient.referenceNumber }]}</br>
                    Pavojingumo lygis: {[{ ingredient.riskLevel }]}</br>
                    CAS numeris: {[{ ingredient.casNumber }]}</br>
                    EC numeris: {[{ ingredient.ecNumber }]}</br>
                    Funkcijos:</br>
                    <c ng-repeat="function in ingredient.functions">&nbsp&nbsp{[{ function }]}</br></c>
                  </p>
                </li>
              </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div ng-hide="!recordsExist" class="ng-hide" class="block1" ng-cloak>
          <h4>Pagal paieškos įvestį duomenų nerasta.. </h4>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}

application/frontendApp/templates/products.html
{% include 'header.html' %}
<div ng-controller="SearchCtrl"
     ng-init="init('/api/productSearch/', '?search=')"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_9">
      <div class="content">
        <div class="block1">
          {% if user.isBrand %}
          <a href="{% url 'frontendApp:createProduct' %}" class="btn">Naujas produktas +</a></br></br>
          {% endif %}
          <input class="searchInput" placeholder="Pagal pavadinimą" type="search" ng-model="searchVar"></input>
          <button ng-click="search(searchVar)">Ieškoti</button>
          </br><a ng-cloak>Rasta: {[{ searchResults.count }]}</a>
          <div ng-cloak ng-hide="recordsExist" class="ng-hide">
            <a href="" ng-click="anotherPage(pageNo-1)" class="btn">< Ankstesnis</a>
            <a href="" ng-cloak ng-repeat="page in pageList track by $index"  ng-click="anotherPage(page)" class="btn">{[{page}]}</a>
            <a href="" ng-click="anotherPage(pageNo+1)" class="btn">Sekantis ></a>
          </div>
        </div>
      </div>
    </div>
    <div class="grid_3">
      <h1><a href="{% url 'frontendApp:top15' %}"><img src="../static/images/logo.png" alt=""></a></h1>
    </div>
    <div class="grid_9">
      <div class="content">
        <div ng-hide="recordsExist" class="ng-hide" class="block1" ng-cloak>
          <div>
            <h3>Produktai:</h3>
            <ul style="list-style: none;"  ng-cloak>
              <li class="grid_9" ng-repeat="product in searchResults.results">
                <div class="grid_2 alpha">
                  <img style="max-width: 120px;" src="{[{ product.thumbnail }]}"></img>
                </div>
                <div class="grid_5">
                  </br>
                  <a href="/produktas/{[{product.pk}]}">{[{ product.name }]}</a></br></br>
                  <a ng-cloak href=""
                     ng-click="showDetails = ! showDetails; changeSign(showDetails, $index)">Aprašymas: <c id="sign{[{$index}]}">+<c>
                     </br>
                  </a>
                  <div ng-show="showDetails">
                    {[{ product.tagLine }]}
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div ng-hide="!recordsExist" class="ng-hide" class="block1" ng-cloak>
          <h4>Pagal paieškos įvestį duomenų nerasta.. </h4>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}

application/frontendApp/templates/register.html
{% include 'header.html' %}
<div ng-controller="RegisterCtrl"
     ng-init="init()"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_9">
      <div class="content">
        <div class="block1">
          <h3>Registracija</h3>
          <ul ng-clock>
            <li><img id="imagePreview" src="#" alt=""></li>
            <li><input file-model="myFile" type="file" id="files" class="ng-hide"/><li>
            <li><label class="pointer" for="files">Pridėti nuotrauką/ logo > *</label></li>
            <li class="red">{[{ errors.image }]}</li>
            <li><input ng-model="registerModel.username"   class="registerForm" maxlength="128" name="username" type="text" placeholder="Slapyvardis">*</li>
            <li class="red">{[{ errors.username }]}</li>
            <li><input ng-model="registerModel.password"   class="registerForm" name="password" type="password" placeholder="Slaptažodis">*</li>
            <li class="red">{[{ errors.password }]}</li>
            <li><input ng-model="registerModel.email"      class="registerForm" maxlength="128" name="email" type="text" placeholder="El.pašto adresas">*</li>
            <li class="red">{[{ errors.email }]}</li>
            <li><textarea ng-model="registerModel.tagLine" class="registerForm" rows="10" placeholder="Trumpas prisistatymas"></textarea></li>
            Registruotis kaip "Prekės ženklas"<input type="checkbox" ng-model="registerModel.isBrand">
            <div ng-clock ng-show="registerModel.isBrand" class="ng-show">
              <li><input ng-model="registerModel.brandName" class="registerForm" maxlength="256" name="brandName" type="text"  placeholder="Prekės ženklo pavadinimas">*</li>
              <li class="red">{[{ errors.brandName }]}</li>
              <li><input ng-model="registerModel.country"   class="registerForm" maxlength="64"  name="country"   type="text"  placeholder="Šalis"></li>
              <li><input ng-model="registerModel.webPage"   class="registerForm" maxlength="128" name="webPage"   type="text" placeholder="Internetinis puslapis"></li>
            </div>
            <li><a ng-click="register()" class="btn">Registruotis</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="grid_3">
      <h1><a href="{% url 'frontendApp:top15' %}"><img src="../static/images/logo.png" alt=""></a></h1>
    </div>
  </div>
</div>
{% include 'footer.html' %}

application/frontendApp/templates/top15.html
{% include 'header.html' %}
{% load static %}
<div ng-controller="Top15Ctrl"
     ng-init="init()"
     class="content_wrapper">
  <div class="container_12">
    <div class="grid_4">
      <div class="content">
        <div style="padding-top: 10px;" class="block1">
          <h4 class="topHeader">TOP 15 produktai</h4>
          <div class="clear"></div></br>
          <div ng-show="productsExist" class="ng-show" class="block1" ng-cloak>
            <ul>
              <li class="top15list" ng-repeat="product in products">
                <div>{[{$index + 1}]}.</div>
                <div><img style="width:50px; margin-left:0px;" src="{% get_media_prefix %}{[{ product.ratedOnProduct__thumbnail }]}"/></div>
                <div style="width:120px; overflow:hidden; text-overflow:ellipsis;"><a href="/produktas/{[{product.ratedOnProduct_id}]}">{[{ product.ratedOnProduct__name }]}</a></div>
                <div>{[{ product.result }]}</div>
              </li>
              <div class="clear"></div>
            </ul>
            <div class="clear"></div>
          </div>
          <div ng-show="!productsExist" class="ng-show" class="block1" ng-cloak>
            <h4>Nėra duomenų</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="grid_4">
      <div class="content">
        <div style="padding-top: 10px;" class="block1">
          <h4 class="topHeader">TOP 15 prekės ženklai</h4>
          <div class="clear"></div></br>
          <div ng-show="brandsExist" class="ng-show" class="block1" ng-cloak>
            <ul>
              <li class="top15list" ng-repeat="brand in brands">
                <div>{[{$index + 1}]}.</div>
                <div><img style="width:50px; margin-left:0px;" src="{% get_media_prefix %}{[{ brand.ratedOnBrand__thumbnail }]}"/></div>
                <div style="width:120px; overflow:hidden; text-overflow:ellipsis;"><a href="/profilis/{[{brand.ratedOnBrand_id}]}">{[{ brand.ratedOnBrand__brandName }]}</a></div>
                <div>{[{ brand.result }]}</div>
              </li>
              <div class="clear"></div>
            </ul>
            <div class="clear"></div>
          </div>
          <div ng-show="!brandsExist" class="ng-show" class="block1" ng-cloak>
            <h4>Nėra duomenų</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="grid_4">
      <div class="content">
        <div style="padding-top: 10px;" class="block1">
          <h4 class="topHeader">TOP 15 naudotojai</h4>
          <div class="clear"></div></br>
          <div ng-show="usersExist" class="ng-show" class="block1" ng-cloak>
            <ul>
              <li class="top15list" ng-repeat="user in users">
                <div>{[{$index + 1}]}.</div>
                <div><img style="width:50px; margin-left:0px;" src="{% get_media_prefix %}{[{ user.ratedOnBrand__thumbnail }]}"/></div>
                <div style="width:120px; overflow:hidden; text-overflow:ellipsis;"><a href="/profilis/{[{user.ratedOnBrand_id}]}">{[{ user.ratedOnBrand__username }]}</a></div>
                <div>{[{ user.result }]}</div>
              </li>
              <div class="clear"></div>
            </ul>
            <div class="clear"></div>
          </div>
          <div ng-show="!usersExist" class="ng-show" class="block1" ng-cloak>
            <h4>Nėra duomenų</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}